services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${OAS_POSTGRES_USER:-ory}
      - POSTGRES_PASSWORD=${OAS_POSTGRES_PASSWORD:-ory-secret}
      - POSTGRES_DB=${OAS_POSTGRES_DB:-ory}
    ports:
      - "${OAS_POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${OAS_POSTGRES_USER:-ory}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Ory Kratos
  kratos:
    image: oryd/kratos:${OAS_KRATOS_VERSION:-v1.1.0}
    ports:
      - "${OAS_KRATOS_PUBLIC_PORT:-4433}:4433"
      - "${OAS_KRATOS_ADMIN_PORT:-4434}:4434"
    environment:
      - DSN=postgres://${OAS_POSTGRES_USER:-ory}:${OAS_POSTGRES_PASSWORD:-ory-secret}@postgres:5432/${OAS_POSTGRES_DB:-ory}?sslmode=disable
      - LOG_LEVEL=${OAS_KRATOS_LOG_LEVEL:-info}
    volumes:
      - ./config/ory-auth-server/kratos:/etc/kratos/
    command: serve -c /etc/kratos/kratos.yml --dev --watch-courier
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Ory hydra migration job
  hydra-migrate:
    image: oryd/hydra:${OAS_HYDRA_VERSION:-v2.2.0}
    environment:
      - DSN=postgres://${OAS_POSTGRES_USER:-ory}:${OAS_POSTGRES_PASSWORD:-ory-secret}@postgres:5432/${OAS_POSTGRES_DB:-ory}?sslmode=disable
    command: migrate sql -e --yes
    depends_on:
      postgres:
        condition: service_healthy

  # Ory Hydra
  hydra:
    image: oryd/hydra:${OAS_HYDRA_VERSION:-v2.2.0}
    ports:
      - "${OAS_HYDRA_PUBLIC_PORT:-4444}:4444"
      - "${OAS_HYDRA_ADMIN_PORT:-4445}:4445"
    environment:
      - DSN=postgres://${OAS_POSTGRES_USER:-ory}:${OAS_POSTGRES_PASSWORD:-ory-secret}@postgres:5432/${OAS_POSTGRES_DB:-ory}?sslmode=disable
      - LOG_LEVEL=${OAS_HYDRA_LOG_LEVEL:-info}
      - SECRETS_SYSTEM=${OAS_HYDRA_SECRETS_SYSTEM:-you-should-change-this-secret}
      - URLS_SELF_ISSUER=${OAS_HYDRA_URLS_SELF_ISSUER:-http://localhost:4444}
      - URLS_LOGIN=${OAS_HYDRA_URLS_LOGIN:-http://localhost:4433/login}
      - URLS_CONSENT=${OAS_HYDRA_URLS_CONSENT:-http://localhost:4433/consent}
      - URLS_ERROR=${OAS_HYDRA_URLS_ERROR:-http://localhost:4433/error}
    volumes:
      - ./config/ory-auth-server/hydra:/etc/hydra/
    command: serve all --dev --config /etc/hydra/hydra.yml
    depends_on:
      postgres:
        condition: service_healthy
      kratos:
        condition: service_started
      hydra-migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  # Kratos self-service UI
  kratos-selfservice-ui:
    image: oryd/kratos-selfservice-ui-node:${OAS_KRATOS_UI_VERSION:-v1.1.0}
    ports:
      - "${OAS_KRATOS_UI_PORT:-4435}:3000"
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - KRATOS_BROWSER_URL=http://localhost:4433
      - COOKIE_SECRET=${OAS_UI_COOKIE_SECRET}
      - CSRF_COOKIE_NAME=${OAS_UI_CSRF_COOKIE_NAME}
      - CSRF_COOKIE_SECRET=${OAS_UI_CSRF_COOKIE_SECRET}
    depends_on:
      - kratos
    restart: unless-stopped
